/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkestmet;

import es.javiergarciescobedo.swing.pluviometro.Pluviometro;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import org.apache.commons.lang3.text.WordUtils;

/**
 *
 * @author Ignacio
 */
public class VentanaEstacionMet extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEstacionMet
     */
    public VentanaEstacionMet() {
        initComponents();

        //Centramos la ventana
        setLocationRelativeTo(null);

        //Iniciamos la Estacion Meteorologica
        iniciarEstacionMet();
    }

    private void iniciarEstacionMet() {
        //Iniciamos el Spinner
        SpinnerModel snpModelNew = new SpinnerNumberModel(1, 1, 31, 1);
        jSDia.setModel(snpModelNew);

        //Iniciamos el Pluviometro
        pararPluviometro();
    }

    private void pararPluviometro() {

        //Activamos el boton Iniciar
        jBIniciar.setEnabled(true);

        //Paramos el resto de botones
        jBParar.setEnabled(false);
        jBMas.setEnabled(false);
        jBMenos.setEnabled(false);
        jBTormentaInmediata.setEnabled(false);

        //Iniciamos el Pluviometro
        setTextoIntensidad();
    }

    private void iniciarPluviometro() {

        //Desactivamos el boton Iniciar
        jBIniciar.setEnabled(false);

        //Iniciamos el resto de botones
        jBParar.setEnabled(true);
        jBMas.setEnabled(true);
        jBMenos.setEnabled(true);
        jBTormentaInmediata.setEnabled(true);

        //Iniciamos el Pluviometro
        setTextoIntensidad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADatos = new javax.swing.JTextArea();
        jBAdd = new javax.swing.JButton();
        jTFCiudad = new javax.swing.JTextField();
        jTFLitros = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSDia = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pluviometro = new es.javiergarciescobedo.swing.pluviometro.Pluviometro();
        jBIniciar = new javax.swing.JButton();
        jBParar = new javax.swing.JButton();
        jBMas = new javax.swing.JButton();
        jBMenos = new javax.swing.JButton();
        jBTormentaInmediata = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTFIntensidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estación Meteorológica");
        setResizable(false);

        jPDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTADatos.setEditable(false);
        jTADatos.setColumns(20);
        jTADatos.setRows(5);
        jScrollPane1.setViewportView(jTADatos);

        jBAdd.setText("Añadir");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Litros:");

        jLabel1.setText("Día:");

        jLabel3.setText("Ciudad:");

        javax.swing.GroupLayout jPDatosLayout = new javax.swing.GroupLayout(jPDatos);
        jPDatos.setLayout(jPDatosLayout);
        jPDatosLayout.setHorizontalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPDatosLayout.createSequentialGroup()
                        .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDatosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSDia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPDatosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBAdd)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPDatosLayout.setVerticalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTFLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBIniciar.setText("Iniciar");
        jBIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarActionPerformed(evt);
            }
        });

        jBParar.setText("Parar");
        jBParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPararActionPerformed(evt);
            }
        });

        jBMas.setText("Más");
        jBMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMasActionPerformed(evt);
            }
        });

        jBMenos.setText("Menos");
        jBMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenosActionPerformed(evt);
            }
        });

        jBTormentaInmediata.setText("Tormenta Inmediata");
        jBTormentaInmediata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTormentaInmediataActionPerformed(evt);
            }
        });

        jLabel4.setText("Intensidad:");

        jTFIntensidad.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pluviometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBMenos)
                            .addComponent(jBIniciar)
                            .addComponent(jBParar)
                            .addComponent(jBMas)))
                    .addComponent(jBTormentaInmediata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jTFIntensidad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pluviometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBParar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBMas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBMenos)))
                .addGap(18, 18, 18)
                .addComponent(jBTormentaInmediata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFIntensidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed

        //Si se han introducido los litros con comas
        jTFLitros.setText(jTFLitros.getText().replace(",", "."));

        //Comprobamos si es Numerico
        if (isNumeric(jTFLitros.getText())) {

            //Si se ha introducido la Ciudad
            if (!jTFCiudad.getText().equals("")) {
                //Recuperamos los Litros
                double numLitros = Double.valueOf(jTFLitros.getText());
                DecimalFormat formatoLitros = new DecimalFormat("# litros");

                //Si el Numero tiene Decimales
                if (jTFLitros.getText().contains(".")) {
                    formatoLitros.applyPattern("#.0 litros");
                }

                //Convertimos la primera letra de la Ciudad a Mayusculas
                jTFCiudad.setText(WordUtils.capitalize(jTFCiudad.getText()));

                //Añadimos la Nueva Informacion
                jTADatos.append(jTFCiudad.getText() + " - Día: " + jSDia.getValue() + " = " + formatoLitros.format(numLitros) + "\n");
            } //Si No se ha introducido la Ciudad --> Error
            else {
                JOptionPane.showMessageDialog(
                        this,
                        "Debe introducir una Ciudad",
                        "Introduzca Ciudad",
                        JOptionPane.ERROR_MESSAGE);
            }
        } //Si ha introducido Texto en vez de Numeros --> Error
        else {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe introducir números en los litros",
                    "No es Numerico",
                    JOptionPane.ERROR_MESSAGE);

            //Ponemos a Nulo el Texto
            jTFLitros.setText("");
        }
    }//GEN-LAST:event_jBAddActionPerformed

    //Valida si se ha introducido un Numero
    private boolean isNumeric(String cadena) {
        try {
            Double.parseDouble(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }


    private void jBIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarActionPerformed

        //Comienza a Llover
        pluviometro.setLloviendo(true);

        //Activamos el Resto de Botones
        iniciarPluviometro();
    }//GEN-LAST:event_jBIniciarActionPerformed

    private void jBPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPararActionPerformed

        //Comienza a Llover
        pluviometro.setLloviendo(false);

        //Desactivamos el Resto de Botones
        pararPluviometro();
    }//GEN-LAST:event_jBPararActionPerformed

    private void jBMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMasActionPerformed

        //Subimos la Intensidad de la Lluvia
        pluviometro.subirIntensidad();
        setTextoIntensidad();
    }//GEN-LAST:event_jBMasActionPerformed

    private void jBMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenosActionPerformed

        //Bajamos la Intensidad de la Lluvia
        pluviometro.bajarIntensidad();

        //Ponemos el Texto con la Intensidad
        setTextoIntensidad();
    }//GEN-LAST:event_jBMenosActionPerformed

    private void jBTormentaInmediataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTormentaInmediataActionPerformed

        pluviometro.setIntensidad(Pluviometro.TORMENTA);
        setTextoIntensidad();
    }//GEN-LAST:event_jBTormentaInmediataActionPerformed

    private void setTextoIntensidad() {
        jTFIntensidad.setText(pluviometro.getIntensidad());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacionMet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacionMet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacionMet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacionMet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstacionMet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBIniciar;
    private javax.swing.JButton jBMas;
    private javax.swing.JButton jBMenos;
    private javax.swing.JButton jBParar;
    private javax.swing.JButton jBTormentaInmediata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPDatos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSDia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADatos;
    private javax.swing.JTextField jTFCiudad;
    private javax.swing.JTextField jTFIntensidad;
    private javax.swing.JTextField jTFLitros;
    private es.javiergarciescobedo.swing.pluviometro.Pluviometro pluviometro;
    // End of variables declaration//GEN-END:variables
}
